# pre-commit 包
-   repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    # 不需要的文件头添加encoding=utf-8
    # -   id: fix-encoding-pragma
    # -   id: autopep8-wrapper
    #     args:
    #     - --in-place
    #     - --ignore=E501,E228,E226,E261,E266,E128,E402,E241
    # -   id: check-added-large-files
    -   id: check-ast
    -   id: check-case-conflict
    -   id: check-docstring-first
    # -   id: check-json
    # -   id: pretty-format-json
    -   id: check-merge-conflict
    -   id: check-xml
    -   id: check-yaml
    -   id: flake8
        args:
        - --ignore=E501,E228,E226,E261,E266,E128,E402,W503,E251,E265
        - --builtins=G,request
        - --jobs=1
        - --exclude=.git,.tox,__pycache__,.eggs,build,*.html, venv/, tmp.py,.vscode
        - --max-line-length=140

    # -   id: end-of-file-fixer
